Setup
Khaled-Alaa-1/Book-store pull request #1
Opened 2023-07-15 10:14 UTC by Khaled-Alaa-1

### In this PR we :

- Could you create a directory for your reusable components: /components?
- Add books list
- Add books form
- Use react-router

2023-07-15 10:59 UTC, wayungi requested changes
Hi @Khaled-Alaa-1 , 

![image](https://user-images.githubusercontent.com/99656687/234198503-c41d0396-d5b0-4466-8ed1-959de33796fa.png)


**Congratulations on the good job done so far!** 🤝 

There are some issues that you still need to work on to go to the next project but you are almost there! 😄 

## Highlights ⚡ ⚡ 
- [ ] All linter checks passing ✔️ 
- [ ]  Correct Git flow ✔️ 
- [ ] Descriptive PR body ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-15 10:59 UTC, wayungi commented on src/App.js
> +          )}
- [ ] Instead of import & buidling all these component inside the App.js, I suggest that you add all these in a separate component (Book) and import only that one component here for use. It will make your code cleaner, more organized and easier to read. 👍🏾 

It would be great it your routes were presented like below

```
<Routes>
        <Route path="/" element={<Books />} />
        <Route path="/categories" element={<Categories />} />
</Routes>

```

2023-07-15 10:59 UTC, wayungi commented on src/App.js
> +  };
- [ ] I suggest you add all these lines of code in the book component and not here. This will help keep your code clean and well organized. 👍🏾

2023-07-15 10:59 UTC, wayungi commented on src/components/books.js
- [ ] Please add the following components in your **Books** component and not in the App.js file

* `<BookList>`
  * Renders a list of books using the `<Book>` component
* `<Book>`
  * Takes the book data as a prop and renders the title and the author
  * Has a button for removing books
* `<NewBookForm>`
  * Renders a form with inputs for the title and the author of the book
  * Has a button to submit
 
This will ensure your code is well organized and its a project requirement as well 👏🏾

2023-07-15 20:22 UTC, Khaled-Alaa-1 commented
I asked for a second opinion from 7h, and I didn't get anything, the added the components in your Books component and not in the App.js file I couldn't find it on the project requirement, and the Routes I was already done.

2023-07-15 20:42 UTC, LionRouge1 approved these changes
Hi @Khaled-Alaa-1, 

# STATUS: APPROVED! 🥇 💯 
Great work on making the changes 👏 
You've done well implementing the requested changes

![done](https://media.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif)

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-07-17 08:26 UTC, ahmetbozaci commented
### Hello @Khaled-Alaa-1 
### _This is an additional review as a result of the second opinion request._ 

- It seems your project is already approved.

___


### Cheers and Happy coding! 💻 👏
____
[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2023-07-19 14:07 UTC, merged